name: Industrialisation continue sur le serveur Alwaysdata

on:
  push:

env:
  SSH_USERNAME: ${{ secrets.USERNAME }}
  SSH_PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  Connexion:
    runs-on: ubuntu-latest
    steps:
      - name: Connexion SSH avec le serveur
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd $HOME/www/

  Copy:
    needs: Connexion
    runs-on: ubuntu-latest
    steps:
      - name: Copie dépôt GitHub -> Alwaysdata
        uses: appleboy/ssh-action@master
        with:
          host: "ssh-${{ secrets.USERNAME }}.alwaysdata.net"
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            last_directory=$(basename ${{ runner.workspace }})
            cd $HOME/
            git clone https://github.com/${{ github.repository }}.git

            if [ "$(ls -A ./www)" ]; then
              rsync -r --delete ./$last_directory/ ./www
              rm -rf ./$last_directory
            else
              echo "Le répertoire www de destination sur votre serveur n'existe pas"
              exit 1
            fi

env:
  SSH_USERNAME: ${{ secrets.USERNAME }}
  SSH_PASSWORD: ${{ secrets.PASSWORD }}
